CREATE TABLE roles (
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    name       VARCHAR(30)  NOT NULL UNIQUE,
    description VARCHAR(200),
    created_at DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6)           DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
);
